import sys
from pathlib import Path

try:
    from fpdf import FPDF
except ImportError as exc:
    raise ImportError(
        "fpdf is not installed. Run `python -m pip install fpdf2` first."
    ) from exc


SCRIPT_DIR = Path(__file__).resolve().parent
FONT_PATH = SCRIPT_DIR / "font.ttf"
FONT_NAME = "CustomFont"


class PDF(FPDF):
    def header(self):
        try:
            self.set_font(FONT_NAME, "", 10)
            self.cell(0, 10, "Generated by Bili Sub Automation", 0, 1, "R")
            self.ln(5)
        except RuntimeError:
            pass

    def footer(self):
        self.set_y(-15)
        try:
            self.set_font(FONT_NAME, "", 8)
            self.cell(0, 10, f"Page {self.page_no()}/{{nb}}", 0, 0, "C")
        except RuntimeError:
            pass


def convert_txt_to_pdf(txt_path):
    txt_file = Path(txt_path).expanduser().resolve()
    if not txt_file.exists():
        print(f"[pdf] missing txt file: {txt_file}")
        return None

    if not FONT_PATH.exists():
        print(f"[pdf] missing font file: {FONT_PATH}")
        return None

    pdf_path = txt_file.with_suffix(".pdf")
    pdf = PDF()
    pdf.alias_nb_pages()

    try:
        pdf.add_font(FONT_NAME, "", str(FONT_PATH))
    except Exception as exc:
        print(f"[pdf] failed to load font: {exc}")
        return None

    pdf.add_page()
    pdf.set_font(FONT_NAME, "", 12)

    try:
        text = txt_file.read_text(encoding="utf-8")
    except Exception as exc:
        print(f"[pdf] failed to read txt: {exc}")
        return None

    title = txt_file.stem
    pdf.set_font(FONT_NAME, "", 16)
    pdf.cell(0, 10, title, 0, 1, "C")
    pdf.ln(10)

    pdf.set_font(FONT_NAME, "", 12)
    pdf.multi_cell(0, 8, text)

    try:
        pdf.output(str(pdf_path))
        print(f"[pdf] written to {pdf_path}")
        return str(pdf_path)
    except Exception as exc:
        print(f"[pdf] failed to save pdf: {exc}")
        return None


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python txt2pdf.py <path_to_txt_file>")
        sys.exit(1)

    output = convert_txt_to_pdf(sys.argv[1])
    sys.exit(0 if output else 1)
